---
# Configures environment variables to set Java location

- name: set java_home environment variable - CentOS
  lineinfile:
     dest='/etc/environment'
     line="export JAVA_HOME=/usr/java/default/jre"
    state=present
  when: ansible_distribution == "CentOS"
